### ISSUE TITLE
Nice work. Does it support....

### ISSUE THREAD

**Issue by CPaxman** [finitelabs/homebridge-control4-home-connect#23]
Nice work. I started a similar driver for Homebridge a few years back, got busy and parked it to work on other Drivers. Keen to see what other drivers you release on DriverCentral.

One of my biggest stumbling blocks when I was looking into this was when two devices had the same name. Even though I based the UUID on the C4 PID it would always seem to break. 

Have you found a way around that?

For example, if you have a APD in the Lounge called Ceiling and then in the Bedroom a APD called Ceiling as well. I was determined that I didnt want to label them Lounge Ceiling and Bedroom Ceiling but wanted them to just be ceiling and would move the loads to a Lounge Room in Homekit and Bedroom in Homekit.

If you want someone else to beta the driver, I'll give it a try for you.

I tested the DTI Technologies driver for them, it was based on the exact same Homebridge plugin I started with.

**Comment by derek-miller** [comment]
Yeah this is the main reason I didnt use the existing websocket plugin. Instead I manage all the UUIDs in the control4 driver and let it maintain the state.
